[package]
name = "homehub"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "2.0.3", features = ["sqlite"] }
dotenv = "0.15.0"
fltk = { version = "1.4.3", features = ["fltk-bundled"] }
uuid = "1.3.0"

[dependencies.rusqlite]
version = "0.29.0"
features = ["bundled"]